name: sonavault
services:
  postgres:
    image: 'postgres:16-alpine'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonavault
    ports:
      - '5432:5432'
    volumes:
      - 'sonavault-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
        - '-d'
        - sonavault
      interval: 5s
      timeout: 20s
      retries: 10

      

volumes:
  sonavault-postgres-data: